version: '3'

services:
  db:
    image: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  omero:
    image: ${OMERO_SERVER_IMAGE}:${OMERO_SERVER_VERSION}
    environment:
      - ROOTPASS=${ROOTPASS}
      - CONFIG_omero_db_user=postgres
      - CONFIG_omero_db_name=postgres
      - CONFIG_omero_db_pass=${POSTGRES_PASSWORD}
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
    ports:
      - "${OMERO_SERVER_TCP}:4063"
      - "${OMERO_SERVER_SSL}:4064"
  web:
    image: ${OMERO_WEB_IMAGE}:${OMERO_WEB_VERSION}
    environment:
      - CONFIG_omero_web_public_enabled=${OMERO_WEB_PUBLIC_ENABLED}
      - CONFIG_omero_web_public_server_id=${OMERO_WEB_PUBLIC_SERVER_ID}
      - CONFIG_omero_web_public_user=${OMERO_WEB_PUBLIC_USER}
      - CONFIG_omero_web_public_password=${OMERO_WEB_PUBLIC_PASSWORD}
      - CONFIG_omero_web_public_url__filter=${OMERO_WEB_PUBLIC_URL_FILTER}
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
    ports:
      - "${OMERO_WEB_PORT}:4080"

# TBD: add client
